import { CalkooCountryVatRates } from '../types';

export const CALKOO_EXPECTED_COUNTRY_VAT_RATES: readonly CalkooCountryVatRates[] = [
  { country: "Afghanistan", shortCode: "AF", ratesPercent: [2, 10] },
  { country: "Albania", shortCode: "AL", ratesPercent: [6, 20] },
  { country: "Algeria", shortCode: "DZ", ratesPercent: [9, 19] },
  { country: "Andorra", shortCode: "AD", ratesPercent: [1, 2.5, 4.5, 9.5] },
  { country: "Angola", shortCode: "AO", ratesPercent: [5, 14] },
  { country: "Anguilla", shortCode: "AI", ratesPercent: [13] },
  { country: "Antigua and Barbuda", shortCode: "AG", ratesPercent: [15] },
  { country: "Argentina", shortCode: "AR", ratesPercent: [2.5, 10.5, 21, 27] },
  { country: "Armenia", shortCode: "AM", ratesPercent: [20] },
  { country: "Aruba", shortCode: "AW", ratesPercent: [3, 7, 12.5] },
  { country: "Australia", shortCode: "AU", ratesPercent: [10] },
  { country: "Austria", shortCode: "AT", ratesPercent: [10, 13, 20] },
  { country: "Azerbaijan", shortCode: "AZ", ratesPercent: [18] },
  { country: "Bahamas", shortCode: "BS", ratesPercent: [12] },
  { country: "Bahrain", shortCode: "BH", ratesPercent: [10] },
  { country: "Bangladesh", shortCode: "BD", ratesPercent: [1.5, 2.25, 4.5, 5, 7.5, 10, 15] },
  { country: "Barbados", shortCode: "BB", ratesPercent: [10, 17.5, 22] },
  { country: "Belarus", shortCode: "BY", ratesPercent: [20] },
  { country: "Belgium", shortCode: "BE", ratesPercent: [6, 12, 21] },
  { country: "Belize", shortCode: "BZ", ratesPercent: [12.5] },
  { country: "Benin", shortCode: "BJ", ratesPercent: [18] },
  { country: "Bhutan", shortCode: "BT", ratesPercent: [7] },
  { country: "Bolivia", shortCode: "BO", ratesPercent: [13] },
  { country: "Bosnia and Herzegovina", shortCode: "BA", ratesPercent: [17] },
  { country: "Botswana", shortCode: "BW", ratesPercent: [12] },
  { country: "Bulgaria", shortCode: "BG", ratesPercent: [9, 10, 20] },
  { country: "Burkina Faso", shortCode: "BF", ratesPercent: [18] },
  { country: "Burundi", shortCode: "BI", ratesPercent: [18] },
  { country: "Cabo Verde", shortCode: "CV", ratesPercent: [15] },
  { country: "Cambodia", shortCode: "KH", ratesPercent: [10] },
  { country: "Cameroon", shortCode: "CM", ratesPercent: [19.25] },
  { country: "Canada", shortCode: "CA", ratesPercent: [5] },
  { country: "Central African Republic (the)", shortCode: "CF", ratesPercent: [19] },
  { country: "Chad", shortCode: "TD", ratesPercent: [18] },
  { country: "Chile", shortCode: "CL", ratesPercent: [19] },
  { country: "Colombia", shortCode: "CO", ratesPercent: [5, 8, 19] },
  { country: "Congo (the Democratic Republic of the)", shortCode: "CD", ratesPercent: [16] },
  { country: "Congo (the)", shortCode: "CG", ratesPercent: [18.9] },
  { country: "Cook Islands (the)", shortCode: "CK", ratesPercent: [15] },
  { country: "Costa Rica", shortCode: "CR", ratesPercent: [13] },
  { country: "Côte d'Ivoire", shortCode: "CI", ratesPercent: [18] },
  { country: "Croatia", shortCode: "HR", ratesPercent: [5, 13, 25] },
  { country: "Cyprus", shortCode: "CY", ratesPercent: [5, 9, 19] },
  { country: "Czech Republic", shortCode: "CZ", ratesPercent: [12, 21] },
  { country: "Denmark", shortCode: "DK", ratesPercent: [25] },
  { country: "Djibouti", shortCode: "DJ", ratesPercent: [10] },
  { country: "Dominica", shortCode: "DM", ratesPercent: [10, 15] },
  { country: "Dominican Republic", shortCode: "DO", ratesPercent: [13, 18] },
  { country: "Ecuador", shortCode: "EC", ratesPercent: [12] },
  { country: "Egypt", shortCode: "EG", ratesPercent: [5, 14] },
  { country: "El Salvador", shortCode: "SV", ratesPercent: [13] },
  { country: "Equatorial Guinea", shortCode: "GQ", ratesPercent: [15] },
  { country: "Estonia", shortCode: "EE", ratesPercent: [9, 13, 22, 24] },
  { country: "Eswatini", shortCode: "SZ", ratesPercent: [15] },
  { country: "Ethiopia", shortCode: "ET", ratesPercent: [15] },
  { country: "Faroe Islands", shortCode: "FO", ratesPercent: [25] },
  { country: "Fiji", shortCode: "FJ", ratesPercent: [9] },
  { country: "Finland", shortCode: "FI", ratesPercent: [10, 13.5, 14, 25.5] },
  { country: "France", shortCode: "FR", ratesPercent: [2.1, 5.5, 10, 20] },
  { country: "FYR Macedonia", shortCode: "MK", ratesPercent: [5, 18] },
  { country: "Gabon", shortCode: "GA", ratesPercent: [18] },
  { country: "Gambia", shortCode: "GM", ratesPercent: [15] },
  { country: "Georgia", shortCode: "GE", ratesPercent: [18] },
  { country: "Germany", shortCode: "DE", ratesPercent: [7, 19] },
  { country: "Ghana", shortCode: "GH", ratesPercent: [3, 5, 15, 20] },
  { country: "Greece", shortCode: "GR", ratesPercent: [6, 13, 24] },
  { country: "Grenada", shortCode: "GD", ratesPercent: [15] },
  { country: "Guatemala", shortCode: "GT", ratesPercent: [12] },
  { country: "Guinea", shortCode: "GN", ratesPercent: [14] },
  { country: "Guinea-Bissau", shortCode: "GW", ratesPercent: [5, 10, 19] },
  { country: "Guyana", shortCode: "GY", ratesPercent: [14] },
  { country: "Haiti", shortCode: "HT", ratesPercent: [10] },
  { country: "Honduras", shortCode: "HN", ratesPercent: [15, 18] },
  { country: "Hungary", shortCode: "HU", ratesPercent: [5, 18, 27] },
  { country: "Iceland", shortCode: "IS", ratesPercent: [11, 24] },
  { country: "India", shortCode: "IN", ratesPercent: [5, 12, 18, 28] },
  { country: "Indonesia", shortCode: "ID", ratesPercent: [12] },
  { country: "Ireland", shortCode: "IE", ratesPercent: [4.8, 9, 13.5, 21, 23] },
  { country: "Islamic Republic of Iran", shortCode: "IR", ratesPercent: [8] },
  { country: "Isle of Man", shortCode: "IM", ratesPercent: [20] },
  { country: "Israel", shortCode: "IL", ratesPercent: [7.5, 17, 18] },
  { country: "Italy", shortCode: "IT", ratesPercent: [4, 5, 10, 22] },
  { country: "Jamaica", shortCode: "JM", ratesPercent: [12.5] },
  { country: "Japan (日本)", shortCode: "JP", ratesPercent: [8, 10] },
  { country: "Jersey", shortCode: "JE", ratesPercent: [5] },
  { country: "Jordan", shortCode: "JO", ratesPercent: [8, 16] },
  { country: "Kazakhstan", shortCode: "KZ", ratesPercent: [12] },
  { country: "Kenya", shortCode: "KE", ratesPercent: [14] },
  { country: "Kiribati", shortCode: "KI", ratesPercent: [12.5] },
  { country: "Kosovo", shortCode: "XK", ratesPercent: [8, 18] },
  { country: "Kyrgyzstan", shortCode: "KG", ratesPercent: [12] },
  { country: "Lao People's Democratic Republic (the)", shortCode: "LA", ratesPercent: [10] },
  { country: "Latvia", shortCode: "LV", ratesPercent: [5, 12, 21] },
  { country: "Lebanon", shortCode: "LB", ratesPercent: [11, 15] },
  { country: "Lesotho", shortCode: "LS", ratesPercent: [14] },
  { country: "Liechtenstein", shortCode: "LI", ratesPercent: [2.6, 3.8, 8.1] },
  { country: "Lithuania", shortCode: "LT", ratesPercent: [5, 9, 12, 21] },
  { country: "Luxembourg", shortCode: "LU", ratesPercent: [3, 8, 14, 17] },
  { country: "Madagascar", shortCode: "MG", ratesPercent: [20] },
  { country: "Malawi", shortCode: "MW", ratesPercent: [16.5] },
  { country: "Malaysia", shortCode: "MY", ratesPercent: [5, 6, 10] },
  { country: "Maldives", shortCode: "MV", ratesPercent: [8] },
  { country: "Mali", shortCode: "ML", ratesPercent: [18] },
  { country: "Malta", shortCode: "MT", ratesPercent: [5, 7, 12, 18] },
  { country: "Mauritania", shortCode: "MR", ratesPercent: [14] },
  { country: "Mauritius", shortCode: "MU", ratesPercent: [15] },
  { country: "Mexico", shortCode: "MX", ratesPercent: [10, 16] },
  { country: "Monaco", shortCode: "MC", ratesPercent: [2.1, 5.5, 10, 20] },
  { country: "Mongolia", shortCode: "MN", ratesPercent: [10] },
  { country: "Montenegro", shortCode: "ME", ratesPercent: [7, 15, 21] },
  { country: "Morocco", shortCode: "MA", ratesPercent: [7, 10, 14, 20] },
  { country: "Mozambique", shortCode: "MZ", ratesPercent: [16] },
  { country: "Namibia", shortCode: "NA", ratesPercent: [15] },
  { country: "Nepal", shortCode: "NP", ratesPercent: [15] },
  { country: "Netherlands", shortCode: "NL", ratesPercent: [9, 21] },
  { country: "New Zealand", shortCode: "NZ", ratesPercent: [9, 15] },
  { country: "Nicaragua", shortCode: "NI", ratesPercent: [15] },
  { country: "Niger (the)", shortCode: "NE", ratesPercent: [19] },
  { country: "Nigeria", shortCode: "NG", ratesPercent: [7.5] },
  { country: "Niue", shortCode: "NU", ratesPercent: [5] },
  { country: "Norway", shortCode: "NO", ratesPercent: [12, 15, 25] },
  { country: "Oman", shortCode: "OM", ratesPercent: [5] },
  { country: "Pakistan", shortCode: "PK", ratesPercent: [1, 17] },
  { country: "Palau", shortCode: "PW", ratesPercent: [10] },
  { country: "Palestine", shortCode: "PS", ratesPercent: [16] },
  { country: "Panama", shortCode: "PA", ratesPercent: [7, 10, 15] },
  { country: "Papua New Guinea", shortCode: "PG", ratesPercent: [10] },
  { country: "Paraguay", shortCode: "PY", ratesPercent: [5, 10] },
  { country: "People's Republic of China (中华人民共和国)", shortCode: "CN", ratesPercent: [3, 6, 9, 13] },
  { country: "Peru", shortCode: "PE", ratesPercent: [18] },
  { country: "Philippines", shortCode: "PH", ratesPercent: [12, 18] },
  { country: "Poland", shortCode: "PL", ratesPercent: [5, 8, 23] },
  { country: "Portugal", shortCode: "PT", ratesPercent: [6, 13, 23] },
  { country: "Republic of Moldova", shortCode: "MD", ratesPercent: [15, 20] },
  { country: "Romania", shortCode: "RO", ratesPercent: [5, 9, 19] },
  { country: "Russia", shortCode: "RU", ratesPercent: [16.67, 20] },
  { country: "Rwanda", shortCode: "RW", ratesPercent: [18] },
  { country: "Saint Kitts and Nevis", shortCode: "KN", ratesPercent: [17] },
  { country: "Saint Lucia", shortCode: "LC", ratesPercent: [12.5] },
  { country: "Saint Vincent and the Grenadines", shortCode: "VC", ratesPercent: [15] },
  { country: "Samoa", shortCode: "WS", ratesPercent: [15] },
  { country: "Saudi Arabia", shortCode: "SA", ratesPercent: [15] },
  { country: "Senegal", shortCode: "SN", ratesPercent: [18] },
  { country: "Serbia", shortCode: "RS", ratesPercent: [10, 20] },
  { country: "Seychelles", shortCode: "SC", ratesPercent: [15] },
  { country: "Sierra Leone", shortCode: "SL", ratesPercent: [15] },
  { country: "Singapore", shortCode: "SG", ratesPercent: [9] },
  { country: "Slovakia", shortCode: "SK", ratesPercent: [5, 19, 23] },
  { country: "Slovenia", shortCode: "SI", ratesPercent: [5, 9.5, 22] },
  { country: "South Africa", shortCode: "ZA", ratesPercent: [15] },
  { country: "South-Korea", shortCode: "KR", ratesPercent: [10] },
  { country: "Spain", shortCode: "ES", ratesPercent: [4, 10, 21] },
  { country: "Sri Lanka", shortCode: "LK", ratesPercent: [15, 18] },
  { country: "Sudan (the)", shortCode: "SD", ratesPercent: [17] },
  { country: "Suriname", shortCode: "SR", ratesPercent: [10] },
  { country: "Sweden", shortCode: "SE", ratesPercent: [6, 12, 25] },
  { country: "Switzerland", shortCode: "CH", ratesPercent: [2.6, 3.8, 8.1] },
  { country: "Taiwan", shortCode: "TW", ratesPercent: [5] },
  { country: "Tajikistan", shortCode: "TJ", ratesPercent: [13] },
  { country: "Tanzania, United Republic of", shortCode: "TZ", ratesPercent: [18] },
  { country: "Thailand", shortCode: "TH", ratesPercent: [7, 10] },
  { country: "Togo", shortCode: "TG", ratesPercent: [18] },
  { country: "Tonga", shortCode: "TO", ratesPercent: [15] },
  { country: "Trinidad and Tobago", shortCode: "TT", ratesPercent: [12.5] },
  { country: "Tunisia", shortCode: "TN", ratesPercent: [7, 13, 19] },
  { country: "Turkey", shortCode: "TR", ratesPercent: [1, 10, 20] },
  { country: "Turkmenistan", shortCode: "TM", ratesPercent: [15] },
  { country: "Uganda", shortCode: "UG", ratesPercent: [18] },
  { country: "Ukraine", shortCode: "UA", ratesPercent: [7, 20] },
  { country: "United Arab Emirates", shortCode: "AE", ratesPercent: [5] },
  { country: "United Kingdom", shortCode: "GB", ratesPercent: [5, 20] },
  { country: "Uruguay", shortCode: "UY", ratesPercent: [10, 22] },
  { country: "Uzbekistan", shortCode: "UZ", ratesPercent: [15] },
  { country: "Vanuatu", shortCode: "VU", ratesPercent: [13] },
  { country: "Venezuela", shortCode: "VE", ratesPercent: [8, 15, 16] },
  { country: "Vietnam", shortCode: "VN", ratesPercent: [5, 8, 10, 15] },
  { country: "Zambia", shortCode: "ZM", ratesPercent: [16] },
  { country: "Zimbabwe", shortCode: "ZW", ratesPercent: [15.5] },
] as const;
